# Generated by Django 5.1 on 2024-08-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(default='', max_length=100)),
                ('codigoProduto', models.CharField(max_length=10)),
                ('descricaoProduto', models.TextField(default='', max_length=500)),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
